# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: anisectlp_01
    shield: anise60b_left 
  - board: anisectlp_01
    shield: anise60b_right 
#  - board: anisectlp_01
#    shield: anise60bn_left 
#  - board: anisectlp_01
#    shield: anise60bn_right 
#  - board: anisectlp_01
#    shield: anise85a_left
#  - board: anisectlp_01
#    shield: anise85a_right
#  - board: anisectlp_01
#    shield: anise85n_left
#  - board: anisectlp_01
#    shield: anise85n_right
#  - board: anisectlc_10
#    shield: anise85n_left
#  - board: anisectlc_10
#    shield: anise85n_right

